name: Update Main Repo

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  update-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout submodule repo
        uses: actions/checkout@v4

      - name: Clone main repo
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git clone --recurse-submodules "$MAIN_REPO_URL" main-repo
        env:
          MAIN_REPO_URL: ${{ secrets.MAIN_REPO_URL }}

      - name: Update submodule in main repo
        run: |
          cd main-repo
          git submodule update --remote Expense_frontend  # update submodule
          git add Expense_frontend  # add the updated submodule
          git commit -m "chore: update submodule to latest commit" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.MAIN_REPO_PAT }}@github.com/username/main-repo.git HEAD:main
